import os
from contextlib import contextmanager

import psycopg
from psycopg.rows import dict_row

SCHEMA = """
CREATE TABLE IF NOT EXISTS jds (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    company TEXT NOT NULL,
    jd_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS resumes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jd_id INTEGER NOT NULL REFERENCES jds(id),
    name TEXT NOT NULL,
    address TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT NOT NULL,
    age TEXT NOT NULL,
    location TEXT NOT NULL,
    resume_text TEXT NOT NULL,
    match_score INTEGER,
    fit_summary TEXT,
    gaps_json TEXT,
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS resumes_jd_id_idx ON resumes (jd_id);
"""


@contextmanager
def db_session():
    """Open a short-lived connection to Neon.

    Serverless functions can't hold a connection between invocations, so each
    request opens and closes its own. Point DATABASE_URL at Neon's *pooled*
    connection string (the host containing "-pooler") so many short-lived
    functions don't exhaust the Postgres connection limit.
    """
    url = os.environ.get("DATABASE_URL")
    if not url:
        raise RuntimeError("DATABASE_URL is not set")

    # psycopg's connection context manager commits on success and rolls back
    # if the body raises; closing is handled by the outer `with`.
    with psycopg.connect(url, row_factory=dict_row) as conn:
        yield conn


def query(sql: str, params: tuple = ()) -> list[dict]:
    with db_session() as conn, conn.cursor() as cur:
        cur.execute(sql, params)
        return cur.fetchall()


def query_one(sql: str, params: tuple = ()) -> dict | None:
    rows = query(sql, params)
    return rows[0] if rows else None


def execute(sql: str, params: tuple = ()) -> None:
    with db_session() as conn, conn.cursor() as cur:
        cur.execute(sql, params)


def init_db() -> None:
    """Create the schema. Run once as a migration, not per request."""
    statements = [s.strip() for s in SCHEMA.split(";") if s.strip()]
    with db_session() as conn, conn.cursor() as cur:
        for statement in statements:
            cur.execute(statement)
